package clases;
// Generated 12-mar-2016 15:24:20 by Hibernate Tools 4.3.1

import java.util.List;
import org.hibernate.Session;
import org.hibernate.Transaction;




/**
 * Nba generated by hbm2java
 */
public class Nba  implements java.io.Serializable {


     private String nombre;
     private Integer edad;
     private String puntos;
     private String rebotes;
      Session sesion;

    public Nba() {
    }

	
    public Nba(String nombre) {
        this.nombre = nombre;
    }
    public Nba(String nombre, Integer edad, String puntos, String rebotes) {
       this.nombre = nombre;
       this.edad = edad;
       this.puntos = puntos;
       this.rebotes = rebotes;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(String puntos) {
        this.puntos = puntos;
    }
    public String getRebotes() {
        return this.rebotes;
    }
    
    public void setRebotes(String rebotes) {
        this.rebotes = rebotes;
    }
 private void iniciaOperacion() throws HibernateException
{
          sesion = NewHibernateUtil.getSessionFactory().openSession();
        Transaction tx = sesion.beginTransaction();
}

       
        
        public List<Nba> obtenListaContactos() throws HibernateException 
{ 
    List<Nba> lista= null;  
    
    try 
    { 
        iniciaOperacion(); 
        lista = sesion.createQuery("from Nba order by RANDOM()").list(); 
    }finally 
    { 
        sesion.close(); 
    }  

    return lista; 
}



}


